### ISSUE TITLE
Add loading view (HUD) to webview

### ISSUE THREAD

**Issue by chwalters** [Glucosio/glucosio-ios#16]
When loading web content the app appears to hang because we have no HUD/ "Loading..." view.  We need to choose a HUD/loading view framework or roll one to add to Glucosio iOS, and then add this to the viewcontrollers that load data from the web pages

**Comment by eugeniobaglieri** [comment]
What about https://github.com/jdg/MBProgressHUD ?

**Comment by chwalters** [comment]
Please try it!

**Comment by eugeniobaglieri** [comment]
I ended using https://github.com/SVProgressHUD/SVProgressHUD.
You can see the final result in the video in the attached file
[gluc-loading-view.zip](https://github.com/Glucosio/glucosio-ios/files/138464/gluc-loading-view.zip)
