### ISSUE TITLE
Add Metrics Parity with Android

### ISSUE THREAD

**Issue by ghost** [Glucosio/glucosio-ios#18]
![f4bb301a-a97e-11e5-83af-0d20980c35fa](https://cloud.githubusercontent.com/assets/859175/13280675/3b13293c-da94-11e5-9539-9efa0e5d271f.jpg)

We need to bring iOS into parity with Android in terms of adding advanced metrics in addition to Glucose see screenshot above.

Icons are here: https://github.com/Glucosio/brand-assets/tree/master/Menu%20Icons

Ping Paolo for tips on how he is storing on Android even though it will be different we should try to use similar conventions.

**Comment by chwalters** [comment]
Closing for functionality but will create another ticket to improve visual/use of icons
