### ISSUE TITLE
Add Tracking

### ISSUE THREAD

**Issue by ghost** [Glucosio/glucosio-ios#2]
Requirements:

I'm unsure what analytics App Store will offer us in regards to active users, active installs and other useful metrics for us but if this is not offered in app store we should investigate a solution,

**Comment by emartynov** [comment]
Here is information and looks like it is enough:
https://developer.apple.com/app-store/app-analytics/

**Comment by chwalters** [comment]
I think this is OBE, feel free to re-open if not
