### ISSUE TITLE
Preventing from following links is needed in ABOUT pages

### ISSUE THREAD

**Issue by ianychoi** [Glucosio/glucosio-ios#33]
### Steps to reproduce
1. Click the 3rd tab: Settings
2. Click "Version", "Terms of use" or "Privacy" in ABOUT section
3. Click any hyperlinks in displayed web page.
### Expected behaviour

The hyperlink does not need to work.
### Actual behaviour

After clicking the links, different pages rather than "Version", "Terms of use" or "Privacy" are shown.

![image](https://cloud.githubusercontent.com/assets/6965982/18098105/b29b4644-6f1b-11e6-8a2b-19367d24fd20.png)

**What language/locale is your device set to use?:**
English

**What measurement system are you using:** 
(Not relavant)

**Are you using backups:** yes/no
no
### Device configuration

**Device:**
iPhone 6s

**Operating system:**
iOS

**Operating system version:**
9.3

**Downloaded App From:**
Testflight
#### Device log

(None)

**Comment by chwalters** [comment]
Hopefully fixed this in 8aad91e
