### ISSUE TITLE
Add indicators for reading levels

### ISSUE THREAD

**Issue by chwalters** [Glucosio/glucosio-ios#40]
As in Android, e.g., 'Hypoglycemia', 'Low', 'Ok', 'High', 'Hyperglycemia'; use same colors as Android

**Comment by mohitagrawal** [comment]
The colors already match to Android colors in iOS file UIColor+GLUCAdditions.m. Do you mean to reference them somewhere?

**Comment by chwalters** [comment]
Yes - we need to match Android's general features.  Example - Android's history view has a color for these reading levels and displays them as a key and the reading in that color

**Comment by emilianbold** [comment]
I don't have Android so I assume you are referring to this view which has a different font color for the value?

![n5-580-277x400](https://user-images.githubusercontent.com/991554/34466823-86b8b378-eee9-11e7-896a-c8bc1b08db9d.png)
