### ISSUE TITLE
Allow users to export data

### ISSUE THREAD

**Issue by chwalters** [Glucosio/glucosio-ios#42]
Investigate manual and automatic exporting of the user's data as CSV (or possibly other formats) to local document storage (for access via iTunes) and possibly iCloud and other cloud services such as Google Drive, Box.com and NextCloud/OwnCloud.  Note this is not about the Research API but about the user being able to save their own data to their own cloud accounts or local disks.

**Comment by emilianbold** [comment]
Note that the Android app only exports glucose readings (see https://github.com/Glucosio/glucosio-android/blob/develop/app/src/main/java/org/glucosio/android/presenter/ExportPresenter.java#L86 )

Maybe we should export a zip file and have a separate CSV file for each reading?
