### ISSUE TITLE
bad user experience in settings viewcontroller

### ISSUE THREAD

**Issue by eugeniobaglieri** [Glucosio/glucosio-ios#9]
i think there is a bad user experience problem in settings viewcontroller when the user have to select the country. The UIPickerView is really small and it take long time to scroll all items (if i want jump to "L" i have to scroll all countries from A to L). Why don't use a tableview instead? Tableview can be also indexed so user can find easly his country. If you want i can take care of this issue. This is the final result:
<img width="487" alt="screenshot 2015-12-18 23 26 20" src="https://cloud.githubusercontent.com/assets/1050414/11908710/dcee09e2-a5de-11e5-96c6-6559bb2c92d7.png">

**Comment by satya164** [comment]
+1

Feel free to send a PR :)

**Comment by chwalters** [comment]
Believe the PR has fixed this one
